#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
###############手动修改##############

name: Test Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      LAN_IP:
        description: 'Set LAN IP Address'
        required: true
        default: '192.168.1.1'
#  schedule:
#    - cron: 0 16 * * *

env:
  UPLOAD_TAG_NAME: rax3000m-emmc
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x
  REPO_BRANCH: openwrt-21.02

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: 准备阶段：缓存加速
      uses: klever1988/cachewrtbuild@main
      with:
        ccache: 'true'  # 启用 ccache，加速构建
        mixkey: 'mt7981'  # 设置目标平台为 R5S 使用的 ramips
        prefix: ${{ github.workspace }}/openwrt  #  使用的源码前缀
      
