#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
###############手动修改##############

name: Test Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      LAN_IP:
        description: 'Set LAN IP Address'
        required: true
        default: '192.168.1.1'
#  schedule:
#    - cron: 0 16 * * *

env:
  ###############手动修改##############
  REPO_URL: https://github.com/uiouio/test
  REPO_BRANCH: main
  FEEDS_CONF: configs/feeds.conf.default
  CONFIG_FILE: configs/.config
  DIY_P1_SH: scripts/diy-part1.sh
  DIY_P2_SH: scripts/diy-part2.sh
  FREE_DISK_SH: scripts/free-disk-space.sh
  DEPENDS_SH: scripts/environment.sh
  CLASH_CORE_SH: scripts/preset-clash-core.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  OPENWRT_NAME: immortalwrt
  UPLOAD_TAG_NAME: mt7981-cmcc-rax3000m-emmc
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: 初始化阶段：设置编译环境
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        #sudo mkdir -p /workdir
        #sudo chown $USER:$GROUPS /workdir
        echo "status=success" >> ${GITHUB_OUTPUT}
  
    - name: 初始化阶段：使用逻辑卷扩大 Github Actions 编译空间
      run: |
        mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
        root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
        sudo truncate -s "${mnt_size}"G /mnt/mnt.img
        sudo truncate -s "${root_size}"G /root.img
        sudo losetup /dev/loop6 /mnt/mnt.img
        sudo losetup /dev/loop7 /root.img
        sudo pvcreate /dev/loop6
        sudo pvcreate /dev/loop7
        sudo vgcreate github /dev/loop6 /dev/loop7
        sudo lvcreate -n runner -l 100%FREE github
        # 创建文件系统并挂载
        # sudo mkfs.xfs /dev/github/runner
        sudo mkfs.ext4 /dev/github/runner
        sudo mkdir -p /builder
        sudo mount /dev/github/runner /builder
        sudo chown -R $USER:$GROUPS /builder
        df -Th

    - name: 准备阶段：克隆固件源码
      working-directory: /builder
      run: |
        df -hT $PWD
        #sudo mkdir -p openwrt
        #sudo chown $USER:$GROUPS openwrt
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /builder/openwrt $GITHUB_WORKSPACE/openwrt
        echon "ls openwrt"
        ls openwrt
        echon "ls $GITHUB_WORKSPACE/openwrt"
        ls $GITHUB_WORKSPACE/openwrt

    - name: 准备阶段：加载feeds.conf.default & 执行自定义脚本DIY_P1_SH
      run: |
        df -hT $PWD
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
